# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux networking PANDA parser.
#

ifeq ($(CONFIG_NET_PANDA),y)
obj-$(CONFIG_NET_PANDA) += panda_parser.o
panda_parser-y := main.c simpleparser_opt.c
endif
